server:
  port: 10110

spring:
  application:
    name: reserve-hub-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lionel13/reserveHub-configurations.git

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show:
        details: always

logging:
  level:
    root: INFO
    org.springframework: INFO
  file:
    name: logs/${spring.application.name}.log